apiVersion: rustcloak.k8s.eboland.de/v1
kind: KeycloakClient
metadata:
  name: example-keycloakrealm
spec:
  realmRef: example-keycloakrealm
  definition:
    clientId: example-client
    name: An example client
