name: Generate Documentation Page
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gather mdbook-version
        id: version
        run: |
          version="$(grep "^version\>" rustcloak-operator/Cargo.toml | cut -d '"' -f 2 | cut -d. -f 1,2)"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
           mdbook-version: 'latest'
      - run: mdbook build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          destination_dir: docs/v${{ steps.version.outputs.version }}
          cname: rustcloak.withlazers.dev
