ARG TARGETARCH

#FROM gcr.io/distroless/static-debian12:nonroot-${TARGETARCH}
FROM alpine:edge

ARG TARGETARCH

COPY artifacts/${TARGETARCH}-unknown-linux-musl/bin/rustcloak /rustcloak

ENTRYPOINT ["/rustcloak"]
